# SPDX-License-Identifier: GPL-2.0

dts-dirs += a52/a52sxq
dts-dirs += m52/m52xq
dts-dirs += gts7/gts7fewifi
dts-dirs += a73/a73xq
dts-dirs += xcover/xcoverpro2
dts-dirs += gtactpro/gtact4pro
dts-dirs += gtactpro/gtact4prowifi

always          := $(dtb-y)
subdir-y        := $(dts-dirs)

clean-files := *.dtb *.reverse.dts *.dtbo


