obj-$(CONFIG_EPEN_WACOM_W9019) += w9019.o
w9019-objs := w9019/wacom_i2c.o w9019/wacom_i2c_sec.o w9019/wacom_i2c_elec.o w9019/w9019_flash.o

obj-$(CONFIG_EPEN_WACOM_WEZ01) += wez01.o
wez01-objs := wez01/wacom_i2c.o wez01/wacom_i2c_sec.o wez01/wacom_i2c_elec.o wez01/wez01_flash.o

ccflags-y += -Wformat
